### ISSUE TITLE
Using the "layouts" helper in v0.6.0

### ISSUE THREAD

**Issue by ghost** [helpers/handlebars-helpers#155]
I'm working on [this issue](https://github.com/assemble/assemble/issues/570), and for that I'm trying to get assemble 0.6.0 up and running with some basic functionality first. Which in my case means building with partials and using the layouts block helpers.

I'm using:

``` json
    "assemble": "git://github.com/assemble/assemble#v0.6.0",
    "consolidate": "^0.10.0",
    "handlebars": "^2.0.0",
    "handlebars-helpers": "git://github.com/assemble/handlebars-helpers#v0.6.0",
```

With an `assemblefile.js` that contains the following:

``` javascript
var assemble = require('assemble');
var engines = require('consolidate');

assemble.engine('hbs', engines.handlebars);
assemble.partials(['lib/**/*.hbs', 'components/**/*.hbs']);

assemble.task('default', function() {
  assemble.src('src/index.hbs', {})
    .pipe(assemble.dest('dist'));
});
```

Now when I run `node node_modules/.bin/assemble` building a page with partials works. It does not parse and insert the front-matter yet, and the layouts block helpers don't work either.
## Layouts

So in order to get the layouts block helpers working I've tried adding this to the `assemblefile.js`:

``` javascript
var helpers = require('handlebars-helpers');
assemble.addHelper('extend', helpers.extend);
```

But that does not work, it throws this error:

``` bash
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Missing helper: 'extend'
    at new Error (<anonymous>)
    at Error.Exception (/assemble_test/node_modules/handlebars/dist/cjs/handlebars/exception.js:13:41)
    at Object.<anonymous> (/assemble_test/node_modules/handlebars/dist/cjs/handlebars/base.js:66:13)
    at Object.eval (eval at <anonymous> (/assemble_test/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:171:23), <anonymous>:3:76)
    at ret (/assemble_test/node_modules/handlebars/dist/cjs/handlebars/runtime.js:137:30)
    at ret (/assemble_test/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:422:21)
    < .. etc >
```

I've also tried using this, which is a little messy, but it does load the extend helper:

``` javascript
var fs = require('fs');
var filepath = './node_modules/handlebars-helpers/lib/helpers/helpers-layouts.js';

assemble.addHelper('extend', function(filepath) {
  return fs.readFileSync(filepath, 'utf8');
});
```

But this way it cannot find the requested layout (which is in the `lib` folder, so should be present in `assemble.partials`):

``` bash
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: ENOENT, no such file or directory 'testlayout'
    at Object.fs.openSync (fs.js:438:18)
    at Object.fs.readFileSync (fs.js:289:15)
    at Object.<anonymous> (/assemble_test/assemblefile.js:11:13)
    at Object.eval (eval at <anonymous> (/assemble_test/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:171:23), <anonymous>:3:76)
    at ret (/assemble_test/node_modules/handlebars/dist/cjs/handlebars/runtime.js:137:30)
    at ret (/assemble_test/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:422:21)
    at Function.exports.handlebars.render (/assemble_test/node_modules/consolidate/lib/consolidate.js:497:14)
    at Function.engine.render (/assemble_test/node_modules/assemble/node_modules/engine-cache/index.js:136:19)
    at View.render (/assemble_test/node_modules/assemble/lib/view/view.js:157:10)
    at Assemble.render (/assemble_test/node_modules/assemble/lib/assemble.js:1116:10)
```

I've tried adding `assemble.layouts(['lib/**/*.hbs', 'components/**/*.hbs']);`, but that results in the exact same error. So I'm wondering if you could tell me what I'm doing wrong here..

**Comment by hinok** [comment]
Hey guys, any updates?

I'm looking for possibility to fill or replace defined ```blocks``` in ```layouts```, based on defined ```pages```.  I'm using ```0.6.0``` with ```gulp-assemble```. In ```0.4``` it could be:

**layout-main.hbs**
```html
<html>
  {{#block "styles"}}{{/block}}
  <body>
    {{#block "body"}}{{/block}}
  </body>
</html>
```

**page1.hbs**
```html
{{#extend "layout-main"}}

    {{#content "styles"}}
      <link rel="stylesheet" href="{{assets}}/css/page1.css">
    {{/content}}

    {{#content "body"}}
      Page 1 content
    {{/content}}

{{/extend}}
```

**page2.hbs**
```html
{{#extend "layout-main"}}

    {{#content "styles"}}
      <link rel="stylesheet" href="{{assets}}/css/page2.css">
    {{/content}}

    {{#content "body"}}
      Page 2 content
    {{/content}}

{{/extend}}
```
