### ISSUE TITLE
helper: set active class on current page

### ISSUE THREAD

**Issue by jonschlinkert** [helpers/handlebars-helpers#9]

**Comment by myorangeca** [comment]
that works but it adds a false text for false values

```
<ul class="nav">
  <li false>
    <a href="./index.html">Home</a>
  </li>
</ul>
```

**Comment by jonschlinkert** [comment]
`{{#is title "Home"}} class="active"{{else}}{{/is}}`

**Comment by Angelita31** [comment]
It doesnot work for me, I got this message Error: Missing helper: "is"
    at Object.<anonymous> (C:\Users\UsuarioHP\AppData\Roaming\npm\nodeauth\node_modules\handlebars\dist\cjs\handlebars\helpers\helper-missing.js:19:13)
    at Object.eval [as main] (eval at createFunctionContext (C:\Users\UsuarioHP\AppData\Roaming\npm\nodeauth\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:254:23), <anonymous>:6:66)
    at main (C:\Users\UsuarioHP\AppData\Roaming\npm\nodeauth\node_modules\handlebars\dist\cjs\handlebars\runtime.js:175:32)
    at ret (C:\Users\UsuarioHP\AppData\Roaming\npm\nodeauth\node_modules\handlebars\dist\cjs\handlebars\runtime.js:178:12)
    at ret (C:\Users\UsuarioHP\AppData\Roaming\npm\nodeauth\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:526:21)
    at ExpressHandlebars._renderTemplate (C:\Users\UsuarioHP\AppData\Roaming\npm\nodeauth\node_modules\express-handlebars\lib\express-handlebars.js:247:12)
    at ExpressHandlebars.<anonymous> (C:\Users\UsuarioHP\AppData\Roaming\npm\nodeauth\node_modules\express-handlebars\lib\express-handlebars.js:173:21)
    at <anonymous>

**Comment by Angelita31** [comment]
This is my code and I get Cannot read property 'includeZero' of undefined
`<ul class="nav navbar-nav">
                 <li{{#if title "Members"}} class="active" {{/if}}>
                   <a class=""href="/">Members</a>
                 </li>
                 <li {{#if title "Register"}} class="active"  {{/if}}><a href="/users/register">Register</a></li>
                 <li {{#if title "Login"}} class="active"  {{/if}}><a href="/users/login">Login</a></li>
               </ul>`

**Comment by doowb** [comment]
@Angelita31 if you have a bug with helpers from `handlebars-helpers`, then please open a new issue for the bug. If you need help with `Handlebars`, then you should ask questions on StackOverflow since more people will see it.

In either case, you should show more information... like how are you registering `handlebars-helpers` with `Handlebars` and how are you compiling and rendering your template?
